[package]
name = "primitives"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]
build = "build.rs"

[dependencies]
heapsize = "0.3"
byteorder = "0.5"
rustc-serialize = "0.3"

[build-dependencies]
rustc_version = "0.1"
