[package]
name = "pbtc"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
bitcrypto = { path = "crypto" }
chain = { path = "chain" }
keys = { path = "keys" }
p2p = { path = "p2p" }
primitives = { path = "primitives" }
script = { path = "script" }
