[package]
name = "pbtc"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
byteorder = "0.5"
rustc-serialize = "0.3"

bitcrypto = { path = "crypto" }
chain = { path = "chain" }
keys = { path = "keys" }
primitives = { path = "primitives" }
serialization = { path = "serialization" }
