[package]
name = "pbtc"
version = "0.1.0"
license = "GPL-3.0"
authors = ["Ethcore <admin@ethcore.io>"]
description = "Parity bitcoin client."

[dependencies]
clap = { version = "2", features = ["yaml"] }
keys = { path = "keys" }
message = { path = "message" }
p2p = { path = "p2p" }
script = { path = "script" }
db = { path = "db" }

[[bin]]
path = "pbtc/main.rs"
name = "pbtc"
