[package]
name = "pbtc"
version = "0.1.0"
license = "GPL-3.0"
authors = ["Ethcore <admin@ethcore.io>"]
description = "Parity bitcoin client."

[dependencies]
log = "0.3"
env_logger = "0.3"
app_dirs = "^1.1.1"
libc = "0.2"
clap = { version = "2", features = ["yaml"] }
chain = { path = "chain" }
keys = { path = "keys" }
message = { path = "message" }
network = { path = "network" }
miner = { path = "miner" }
p2p = { path = "p2p" }
script = { path = "script" }
db = { path = "db" }
verification = { path = "verification" }
sync = { path = "sync" }
import = { path = "import" }
bencher = { path = "bencher" }
logs = { path = "logs" }
rpc = { path = "rpc" }
primitives = { path = "primitives" }

# remove me after new version of tokio-core is released + run cargo update
[replace]
"tokio-core:0.1.3" = { git = "https://github.com/tokio-rs/tokio-core.git", rev = "d0833074d6c47970b69baf69702c92a497c93fc2" }

[[bin]]
path = "pbtc/main.rs"
name = "pbtc"

[workspace]
