[package]
name = "pbtc"
version = "0.1.0"
license = "GPL-3.0"
authors = ["Ethcore <admin@ethcore.io>"]
description = "Parity bitcoin client."

[dependencies]
clap = { version = "2", features = ["yaml"] }
tokio-core = "0.1"
futures = "0.1"

bitcrypto = { path = "crypto" }
chain = { path = "chain" }
keys = { path = "keys" }
message = { path = "message" }
p2p = { path = "p2p" }
primitives = { path = "primitives" }
script = { path = "script" }

[[bin]]
path = "pbtc/main.rs"
name = "pbtc"
