[package]
name = "verification"
version = "0.1.0"
authors = ["Nikolay Volf <nikvolf@gmail.com>"]

[dependencies]
byteorder = "0.5"
parking_lot = "0.3"
time = "0.1"
log = "0.3"
scoped-pool = "1.0"
rayon = "0.5"

ethcore-devtools = { path = "../devtools" }
primitives = { path = "../primitives" }
chain = { path = "../chain"  }
serialization = { path = "../serialization" }
test-data = { path = "../test-data" }
script = { path = "../script" }
network = { path = "../network" }
db = { path = "../db", features = ["dev"] }
