[package]
name = "network"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
serialization = { path = "../serialization" }
chain = { path = "../chain" }
primitives = { path = "../primitives" }
