[package]
name = "miner"
version = "0.1.0"
authors = ["Ethcore <admin@ethcore.io>"]

[dependencies]
heapsize = "0.3"
chain = { path = "../chain" }
db = { path = "../db" }
primitives = { path = "../primitives" }
serialization = { path = "../serialization" }
test-data = { path = "../test-data" }
