[package]
name = "bitcrypto"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
rust-crypto = "0.2.36"
primitives = { path = "../primitives" }

[dependencies.clippy]
optional = true
version = "0.0.97"

[features]
default = []
dev = ["clippy", "primitives/dev"]
